### ISSUE TITLE
any Plans for a new release?

### ISSUE THREAD

**Issue by nopeppermint** [UltraStar-Deluxe/UltraStar-Manager#10]

**Comment by JPGsProfil** [comment]
First of all: Thanks for this great tool and thank you for developing it!!! 
Is there any chance to get a new release (or another way to get a precompiled current version) of Ultrastar-Manager? Because it seem's to be that the old release 1.8.3 has a problem with utf8-files (new standard for all tools? (https://usdx.eu/format/#together-with)) which seem to be fixed years ago on github. This would help me and others who habe problems building it on their own.
Kind regards

**Comment by DeinAlptraum** [comment]
While there's no new release yet, you can find up-to-date builds for all platforms on the latest CI run.
Just go here: https://github.com/UltraStar-Deluxe/UltraStar-Manager/actions/runs/8753702409
and scroll to the bottom.
